# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dougbtv
tagline:          'tech-nine, bust an AK'
description:      'Linux. Full-stack JavaScript. Web apps. Asterisk. Hacking. <a href="https://twitter.com/dougbtv" target="_blank">@dougbtv</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'dougbtv'
  url:            https://twitter.com/dougbtv

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

accounts:
  github:         https://github.com/dougbtv
  stackexchange:  http://stackoverflow.com/users/1681171/dougbtv